---
title: "Regression with trees"
author: "Philippe Grosjean"
date: "11/6/2015"
output: html_notebook
---

```{r}
SciViews::R
trees <- read("trees", package = "datasets", lang = "fr")
summary(trees)
```

```{r}
corrplot::corrplot(cor(trees[, 1:3],
  use = "pairwise.complete.obs"), method = "ellipse")
```

```{r}
summary(lm. <- lm(data = trees, volume ~ diameter))
lm. %>% (function(lm, model = lm[["model"]], vars = names(model))
  ggplot(model, aes_string(x = vars[2], y = vars[1])) +
  geom_point() + stat_smooth(method = "lm", formula = y ~ x))
```

```{r}
#plot(lm., which = 1)
lm. %>% qplot(.fitted, .resid, data = .) +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE) +
  xlab("Fitted values") +
  ylab("Residuals") +
  ggtitle("Residuals vs Fitted")
```

```{r}
#plot(lm., which = 2)
lm. %>% qplot(sample = .stdresid, data = .) +
  geom_abline(intercept = 0, slope = 1, colour = "darkgray") +
  xlab("Theoretical quantiles") +
  ylab("Standardized residuals") +
  ggtitle("Normal Q-Q")
```

```{r}
summary(lm. <- lm(data = trees, volume ~ diameter + height))
```

```{r}
summary(lm. <- lm(data = trees, volume ~  diameter + I(diameter^2)))
lm. %>% (function(lm, model = lm[["model"]], vars = names(model))
  ggplot(model, aes_string(x = vars[2], y = vars[1])) +
  geom_point() + stat_smooth(method = "lm", formula = y ~ x + I(x^2)))
```

```{r}
summary(lm. <- lm(data = trees, volume ~ diameter + I(diameter^2) + height))

```

```{r}
summary(lm. <- lm(data = trees, volume ~ diameter + I(diameter^2) + height - 1))

```

```{r}
#plot(lm., which = 1)
lm. %>% qplot(.fitted, .resid, data = .) +
  geom_hline(yintercept = 0) +
  geom_smooth(se = FALSE) +
  xlab("Fitted values") +
  ylab("Residuals") +
  ggtitle("Residuals vs Fitted")
```

```{r}
#plot(lm., which = 2)
lm. %>% qplot(sample = .stdresid, data = .) +
  geom_abline(intercept = 0, slope = 1, colour = "darkgray") +
  xlab("Theoretical quantiles") +
  ylab("Standardized residuals") +
  ggtitle("Normal Q-Q")
```

```{r}
AIC(lm.)
```

